name: jenga
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
      # add here only pip-packages that are not available in conda/conda-forge! E.g.:
      - tensorflow
      - tensorflow-data-validation
      - keras
      - imgaug
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - pylint
  - pydocstyle
